[package]
name = "gnn"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.18.0", features = ["autodiff", "wgpu", "autotune", "template"] }
bytemuck = "1.23.1"
cubecl = { version = "0.6.0", features = ["wgpu"] }
derive-new = "0.7.0"
log = "0.4.27"
serde = "1.0.219"
